name: Build and deploy .NET application to container app addressdata-backend
on:
  push:
    branches:
    - feat/cicd
env:
  CONTAINER_APP_CONTAINER_NAME: addressdatabackend
  CONTAINER_APP_NAME: addressdata-backend
  CONTAINER_APP_RESOURCE_GROUP_NAME: addressdata-rg
  CONTAINER_REGISTRY_LOGIN_SERVER: containerplace.azurecr.io
  DOCKER_FILE_PATH: src/AddressData.WebApi/Dockerfile
  PROJECT_NAME_FOR_DOCKER: addressdatawebapi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.containerplace_USERNAME_BB72 }}
        password: ${{ secrets.containerplace_PASSWORD_BB72 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
